sudo: false
matrix:
  fast_finish: true
language: ruby
rvm:
  - 2.3.1
  - 1.9.2
  - 1.8.7
before_install:
  - gem update bundler
after_success:
  - ruby -e 'exit RUBY_VERSION > "2"' && bundle exec codeclimate-test-reporter
notifications:
  email: false
